apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: demo-svc-primary
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: demo-svc-primary
  type: ClusterIP
status:
  loadBalancer: {}
